version: '3.9'

services:
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: test

  rabbitmq:
    image: rabbitmq:management
    hostname: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_VHOST: /
    networks:
      - rabbitmq_net

  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379

networks:
  rabbitmq_net:
    driver: bridge 